### PR TITLE
Add Flutter Export

### PR DESCRIPTION
**Pull request by vstollen**
Adds `Flutter MaterialColor` as an export option, as a slightly altered variant of #106.

The generated code resembles a `MaterialColor` dart object.

### CODE REVIEW

**Comment by stefanrusek** [comment]
@mbitson I find your color tool super useful, but using it with flutter is kind of a pain. This PR would make things a lot easier.

**Comment by berryp** [comment]
This is great! However, it would be better if the generated code used the same format as the colours defined in the Flutter source. E.g.

```dart
// flutter/lib/src/material/colors.dart
static const MaterialColor blue = MaterialColor(
  _bluePrimaryValue,
  <int, Color>{
    50: Color(0xFFE3F2FD),
    100: Color(0xFFBBDEFB),
    200: Color(0xFF90CAF9),
    300: Color(0xFF64B5F6),
    400: Color(0xFF42A5F5),
    500: Color(_bluePrimaryValue),
    600: Color(0xFF1E88E5),
    700: Color(0xFF1976D2),
    800: Color(0xFF1565C0),
    900: Color(0xFF0D47A1),
  },
);
static const int _bluePrimaryValue = 0xFF2196F3;

static const MaterialAccentColor blueAccent = MaterialAccentColor(
  _blueAccentPrimaryValue,
  <int, Color>{
    100: Color(0xFF82B1FF),
    200: Color(_blueAccentPrimaryValue),
    400: Color(0xFF2979FF),
    700: Color(0xFF2962FF),
  },
);
static const int _blueAccentPrimaryValue = 0xFF448AFF;
```

**Comment by berryp** [comment]
I've created a pull request against @vstollen's branch https://github.com/vstollen/mcg/pull/1.

@vstollen If you'd rather I create a fresh PR here instead, I'd be happy to do so.

**Comment by RodolfoSilva** [comment]
http://mcg.rodolfosilva.com/

**Review by mbitson — APPROVED** [review]
This looks great, thank you to everyone who helped and contributed on this!

**Pull request merged**
